'use strict';
/* Answer-file generation (form state → unattend XML) and form-level validation.
 * Pass layout: windowsPE (language, disk, image, UserData) → specialize (name,
 * network, domain, RDP, RunSynchronous) → oobeSystem (locale, accounts, OOBE,
 * FirstLogonCommands). */

function buildXml(s){
  const b = new XB();
  b.raw('<?xml version="1.0" encoding="utf-8"?>');
  b.raw('<!-- Generated by Golden Image Generator - ' + esc(imageName(s)) + ' -->');
  b.open('unattend xmlns="urn:schemas-microsoft-com:unattend"');

  /* ---------- windowsPE ---------- */
  b.open('settings pass="windowsPE"');

  b.open(`component name="Microsoft-Windows-International-Core-WinPE" ${CATTRS}`);
  b.open('SetupUILanguage');
  b.leaf('UILanguage', s.uilang);
  b.close();
  b.leaf('InputLocale', s.inlocale);
  b.leaf('SystemLocale', s.syslocale);
  b.leaf('UILanguage', s.uilang);
  b.leaf('UserLocale', s.userlocale);
  b.close();

  b.open(`component name="Microsoft-Windows-Setup" ${CATTRS}`);
  const osPartition = s.firmware === 'uefi' ? 3 : 2;

  if (s.diskEnable){
    b.open('DiskConfiguration');
    b.open('Disk wcm:action="add"');
    b.leaf('DiskID', s.diskId);
    b.leaf('WillWipeDisk', 'true');
    b.open('CreatePartitions');
    if (s.firmware === 'uefi'){
      b.open('CreatePartition wcm:action="add"');
      b.leaf('Order', 1); b.leaf('Type', 'EFI'); b.leaf('Size', s.efiSize);
      b.close();
      b.open('CreatePartition wcm:action="add"');
      b.leaf('Order', 2); b.leaf('Type', 'MSR'); b.leaf('Size', 16);
      b.close();
      b.open('CreatePartition wcm:action="add"');
      b.leaf('Order', 3); b.leaf('Type', 'Primary'); b.leaf('Extend', 'true');
      b.close();
    } else {
      b.open('CreatePartition wcm:action="add"');
      b.leaf('Order', 1); b.leaf('Type', 'Primary'); b.leaf('Size', 100);
      b.close();
      b.open('CreatePartition wcm:action="add"');
      b.leaf('Order', 2); b.leaf('Type', 'Primary'); b.leaf('Extend', 'true');
      b.close();
    }
    b.close(); // CreatePartitions
    b.open('ModifyPartitions');
    if (s.firmware === 'uefi'){
      b.open('ModifyPartition wcm:action="add"');
      b.leaf('Order', 1); b.leaf('PartitionID', 1); b.leaf('Label', 'System'); b.leaf('Format', 'FAT32');
      b.close();
      b.open('ModifyPartition wcm:action="add"');
      b.leaf('Order', 2); b.leaf('PartitionID', 3); b.leaf('Label', s.osLabel); b.leaf('Letter', 'C'); b.leaf('Format', 'NTFS');
      b.close();
    } else {
      b.open('ModifyPartition wcm:action="add"');
      b.leaf('Order', 1); b.leaf('PartitionID', 1); b.leaf('Label', 'System'); b.leaf('Format', 'NTFS'); b.leaf('Active', 'true');
      b.close();
      b.open('ModifyPartition wcm:action="add"');
      b.leaf('Order', 2); b.leaf('PartitionID', 2); b.leaf('Label', s.osLabel); b.leaf('Letter', 'C'); b.leaf('Format', 'NTFS');
      b.close();
    }
    b.close(); // ModifyPartitions
    b.close(); // Disk
    b.leaf('WillShowUI', 'OnError');
    b.close(); // DiskConfiguration
  }

  if (s.imageMode !== 'none' || s.diskEnable){
    b.open('ImageInstall');
    b.open('OSImage');
    if (s.imageMode === 'name'){
      b.open('InstallFrom');
      b.open('MetaData wcm:action="add"');
      b.leaf('Key', '/IMAGE/NAME');
      b.leaf('Value', imageName(s));
      b.close();
      b.close();
    } else if (s.imageMode === 'index'){
      b.open('InstallFrom');
      b.open('MetaData wcm:action="add"');
      b.leaf('Key', '/IMAGE/INDEX');
      b.leaf('Value', s.imageIndex);
      b.close();
      b.close();
    }
    if (s.diskEnable){
      b.open('InstallTo');
      b.leaf('DiskID', s.diskId);
      b.leaf('PartitionID', osPartition);
      b.close();
    }
    b.leaf('WillShowUI', 'OnError');
    b.close(); // OSImage
    b.close(); // ImageInstall
  }

  b.open('UserData');
  b.leaf('AcceptEula', bool(s.eula));
  if (s.fullname) b.leaf('FullName', s.fullname);
  if (s.org) b.leaf('Organization', s.org);
  if (s.key){
    b.open('ProductKey');
    b.leaf('Key', s.key);
    b.leaf('WillShowUI', 'OnError');
    b.close();
  }
  b.close(); // UserData
  b.close(); // component Setup
  b.close(); // settings windowsPE

  /* ---------- specialize ---------- */
  b.open('settings pass="specialize"');

  b.open(`component name="Microsoft-Windows-Shell-Setup" ${CATTRS}`);
  if (s.compname) b.leaf('ComputerName', s.compname);
  if (s.org) b.leaf('RegisteredOrganization', s.org);
  if (s.fullname) b.leaf('RegisteredOwner', s.fullname);
  if (s.tz) b.leaf('TimeZone', s.tz);
  b.close();

  if (s.netEnable && s.ifid && s.ip){
    b.open(`component name="Microsoft-Windows-TCPIP" ${CATTRS}`);
    b.open('Interfaces');
    b.open('Interface wcm:action="add"');
    b.leaf('Identifier', s.ifid);
    b.open('Ipv4Settings');
    b.leaf('DhcpEnabled', 'false');
    b.leaf('RouterDiscoveryEnabled', 'false');
    b.close();
    b.open('UnicastIpAddresses');
    b.leaf('IpAddress wcm:action="add" wcm:keyValue="1"', s.ip);
    b.close();
    if (s.gw){
      b.open('Routes');
      b.open('Route wcm:action="add"');
      b.leaf('Identifier', 0);
      b.leaf('Prefix', '0.0.0.0/0');
      b.leaf('NextHopAddress', s.gw);
      b.close();
      b.close();
    }
    b.close(); // Interface
    b.close(); // Interfaces
    b.close();

    if (s.dns1 || s.dnsdomain){
      b.open(`component name="Microsoft-Windows-DNS-Client" ${CATTRS}`);
      b.open('Interfaces');
      b.open('Interface wcm:action="add"');
      b.leaf('Identifier', s.ifid);
      if (s.dnsdomain) b.leaf('DNSDomain', s.dnsdomain);
      if (s.dns1){
        b.open('DNSServerSearchOrder');
        b.leaf('IpAddress wcm:action="add" wcm:keyValue="1"', s.dns1);
        if (s.dns2) b.leaf('IpAddress wcm:action="add" wcm:keyValue="2"', s.dns2);
        b.close();
      }
      b.close();
      b.close();
      b.close();
    }
  }

  if (s.joinMode === 'domain' && s.domain){
    b.open(`component name="Microsoft-Windows-UnattendedJoin" ${CATTRS}`);
    b.open('Identification');
    if (s.joinCredUser){
      b.open('Credentials');
      b.leaf('Domain', s.joinCredDomain || s.domain);
      b.leaf('Password', s.joinCredPw);
      b.leaf('Username', s.joinCredUser);
      b.close();
    }
    b.leaf('JoinDomain', s.domain);
    if (s.ou) b.leaf('MachineObjectOU', s.ou);
    b.close();
    b.close();
  } else if (s.joinMode === 'workgroup' && s.workgroup){
    b.open(`component name="Microsoft-Windows-UnattendedJoin" ${CATTRS}`);
    b.open('Identification');
    b.leaf('JoinWorkgroup', s.workgroup);
    b.close();
    b.close();
  }

  // IE ESC does not exist on Server 2025+ (IE was removed), so emit only for 2019/2022
  if (s.ieesc && s.version !== '2025'){
    b.open(`component name="Microsoft-Windows-IE-ESC" ${CATTRS}`);
    b.leaf('IEHardenAdmin', 'false');
    b.leaf('IEHardenUser', 'false');
    b.close();
  }

  if (s.rdp){
    b.open(`component name="Microsoft-Windows-TerminalServices-LocalSessionManager" ${CATTRS}`);
    b.leaf('fDenyTSConnections', 'false');
    b.close();
    b.open(`component name="Microsoft-Windows-TerminalServices-RDP-WinStationExtensions" ${CATTRS}`);
    b.leaf('SecurityLayer', 2);
    b.leaf('UserAuthentication', s.nla ? 1 : 0);
    b.close();
    if (s.fw){
      b.open(`component name="Networking-MPSSVC-Svc" ${CATTRS}`);
      b.open('FirewallGroups');
      b.open('FirewallGroup wcm:action="add" wcm:keyValue="RemoteDesktop"');
      b.leaf('Active', 'true');
      b.leaf('Group', '@FirewallAPI.dll,-28752');
      b.leaf('Profile', 'all');
      b.close();
      b.close();
      b.close();
    }
  }

  const runCmds = [];
  if (s.power) runCmds.push({ cmd: TWEAK_CMDS.power, desc: 'High performance power plan' });
  if (s.srvmgr) runCmds.push({ cmd: TWEAK_CMDS.srvmgr, desc: 'Do not open Server Manager at logon' });
  s.runSync.filter(r => r.cmd.trim()).forEach(r => runCmds.push({ cmd: r.cmd.trim(), desc: r.desc.trim() }));

  if (runCmds.length){
    b.open(`component name="Microsoft-Windows-Deployment" ${CATTRS}`);
    b.open('RunSynchronous');
    runCmds.forEach((c, i) => {
      b.open('RunSynchronousCommand wcm:action="add"');
      b.leaf('Order', i + 1);
      b.leaf('Path', c.cmd);
      if (c.desc) b.leaf('Description', c.desc);
      b.close();
    });
    b.close();
    b.close();
  }
  b.close(); // settings specialize

  /* ---------- oobeSystem ---------- */
  b.open('settings pass="oobeSystem"');

  b.open(`component name="Microsoft-Windows-International-Core" ${CATTRS}`);
  b.leaf('InputLocale', s.inlocale);
  b.leaf('SystemLocale', s.syslocale);
  b.leaf('UILanguage', s.uilang);
  b.leaf('UserLocale', s.userlocale);
  b.close();

  b.open(`component name="Microsoft-Windows-Shell-Setup" ${CATTRS}`);

  if (s.autologon && s.adminpw){
    b.open('AutoLogon');
    pwNode(b, 'Password', s.adminpw, s.obfuscate, 'Password');
    b.leaf('Enabled', 'true');
    b.leaf('LogonCount', s.logoncount);
    b.leaf('Username', 'Administrator');
    b.close();
  }

  const flCmds = [];
  if (s.packerWinrm) PACKER_WINRM_CMDS.forEach(c => flCmds.push({ cmd: c.cmd, desc: c.desc }));
  if (s.psremote) flCmds.push({ cmd: TWEAK_CMDS.psremote, desc: 'Enable PowerShell remoting' });
  s.firstLogon.filter(r => r.cmd.trim()).forEach(r => flCmds.push({ cmd: r.cmd.trim(), desc: r.desc.trim() }));
  if (flCmds.length){
    b.open('FirstLogonCommands');
    flCmds.forEach((c, i) => {
      b.open('SynchronousCommand wcm:action="add"');
      b.leaf('Order', i + 1);
      b.leaf('CommandLine', c.cmd);
      if (c.desc) b.leaf('Description', c.desc);
      b.close();
    });
    b.close();
  }

  b.open('OOBE');
  b.leaf('HideEULAPage', bool(s.hideEula));
  b.leaf('HideLocalAccountScreen', bool(s.hideLocal));
  b.leaf('HideOEMRegistrationScreen', bool(s.hideOem));
  b.leaf('HideOnlineAccountScreens', bool(s.hideOnline));
  b.leaf('HideWirelessSetupInOOBE', bool(s.hideWireless));
  b.leaf('ProtectYourPC', s.pypc);
  b.close();

  if (s.org) b.leaf('RegisteredOrganization', s.org);
  if (s.fullname) b.leaf('RegisteredOwner', s.fullname);

  const extraAccounts = s.accounts.filter(a => a.name.trim());
  if (s.adminpw || extraAccounts.length){
    b.open('UserAccounts');
    if (s.adminpw) pwNode(b, 'AdministratorPassword', s.adminpw, s.obfuscate, 'AdministratorPassword');
    if (extraAccounts.length){
      b.open('LocalAccounts');
      extraAccounts.forEach(a => {
        b.open('LocalAccount wcm:action="add"');
        if (a.password) pwNode(b, 'Password', a.password, s.obfuscate, 'Password');
        if (a.desc) b.leaf('Description', a.desc);
        b.leaf('DisplayName', a.display || a.name);
        b.leaf('Group', a.group || 'Administrators');
        b.leaf('Name', a.name.trim());
        b.close();
      });
      b.close();
    }
    b.close();
  }

  b.close(); // component Shell-Setup
  b.close(); // settings oobeSystem

  b.close(); // unattend
  return b.toString();
}

/* ---------- validation ---------- */
function validate(s){
  const errs = [];
  const IP_RE = /^\d{1,3}(\.\d{1,3}){3}$/;
  if (s.compname && s.compname !== '*' && !/^[A-Za-z0-9-]{1,15}$/.test(s.compname))
    errs.push('Computer name must be 1–15 chars, letters/digits/hyphens only (or * for random).');
  if (s.key && !/^[A-Za-z0-9]{5}(-[A-Za-z0-9]{5}){4}$/.test(s.key))
    errs.push('Product key format looks wrong (expected XXXXX-XXXXX-XXXXX-XXXXX-XXXXX).');
  if (s.autologon && !s.adminpw)
    errs.push('Auto-logon is enabled but no Administrator password is set.');
  if (!s.adminpw)
    errs.push('No Administrator password is set — Server OOBE will stop and ask for one, so the install is not fully unattended.');
  if (s.evalMedia && s.key)
    errs.push('Evaluation media cannot use volume-license/retail keys — leave the product key blank for eval installs.');
  if (s.packerWinrm && (!s.autologon || !s.adminpw))
    errs.push('The Packer WinRM bootstrap runs as first-logon commands — set an Administrator password and enable auto-logon so they run without a manual logon.');
  if (s.netEnable){
    if (!/^\d{1,3}(\.\d{1,3}){3}\/\d{1,2}$/.test(s.ip)) errs.push('Static IP must be CIDR notation, e.g. 192.168.0.50/24.');
    if (s.gw && !IP_RE.test(s.gw)) errs.push('Gateway is not a valid IPv4 address.');
    if (s.dns1 && !IP_RE.test(s.dns1)) errs.push('DNS server 1 is not a valid IPv4 address.');
    if (s.dns2 && !IP_RE.test(s.dns2)) errs.push('DNS server 2 is not a valid IPv4 address.');
  }
  if (s.joinMode === 'domain'){
    if (!s.domain) errs.push('Domain join selected but no domain FQDN entered.');
    else if (s.joinCredUser && !s.joinCredPw) errs.push('Domain-join username set but its password is empty.');
  }
  s.accounts.filter(a => a.name.trim()).forEach(a => {
    if (!/^[^"/\\\[\]:;|=,+*?<>@]{1,20}$/.test(a.name.trim()))
      errs.push(`Local account name “${a.name}” is invalid.`);
  });
  return errs;
}
